#!/usr/bin/env bun

/**
 * 将 webui/dist 目录中的静态文件嵌入到 src/server/embedded-webui.ts
 * 所有文件都会被 base64 编码
 */

import { readdir, readFile, writeFile, stat } from "fs/promises";
import { join, extname } from "path";

const WEBUI_DIST = join(import.meta.dir, "../webui/dist");
const OUTPUT_FILE = join(import.meta.dir, "../src/server/embedded-webui.ts");

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html",
  ".js": "application/javascript",
  ".css": "text/css",
  ".json": "application/json",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
};

interface EmbeddedFile {
  content: string; // base64 encoded
  contentType: string;
}

async function getAllFiles(dir: string, baseDir: string = dir): Promise<string[]> {
  const files: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await getAllFiles(fullPath, baseDir)));
    } else {
      // 获取相对路径
      const relativePath = fullPath.slice(baseDir.length + 1);
      files.push(relativePath);
    }
  }

  return files;
}

async function main() {
  console.log("📦 Embedding WebUI files...\n");

  // 检查 dist 目录是否存在
  try {
    await stat(WEBUI_DIST);
  } catch {
    console.error("❌ Error: webui/dist directory not found.");
    console.error("   Run 'cd webui && bun run build' first.");
    process.exit(1);
  }

  const files = await getAllFiles(WEBUI_DIST);
  const embeddedFiles: Record<string, EmbeddedFile> = {};

  let totalSize = 0;

  for (const file of files) {
    const fullPath = join(WEBUI_DIST, file);
    const content = await readFile(fullPath);
    const ext = extname(file);
    const contentType = MIME_TYPES[ext] || "application/octet-stream";

    embeddedFiles[file] = {
      content: content.toString("base64"),
      contentType,
    };

    totalSize += content.length;
    console.log(`  ✓ ${file} (${formatSize(content.length)})`);
  }

  // 生成 TypeScript 文件
  const output = `// Auto-generated by scripts/embed-webui.ts
// Do not edit manually

export const files: Record<string, { content: string; contentType: string }> = ${JSON.stringify(embeddedFiles, null, 2)};
`;

  await writeFile(OUTPUT_FILE, output);

  console.log(`\n✅ Embedded ${files.length} files (${formatSize(totalSize)} total)`);
  console.log(`   Output: ${OUTPUT_FILE}`);
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
