name: Build Windows App (Test)

on:
  workflow_dispatch:
  push:
    branches: [test-windows]

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install

      - run: pnpm run build -- --publish never

      - uses: actions/upload-artifact@v4
        with:
          name: windows-app-build
          path: |
            release/*.exe
            release/*.zip
          retention-days: 1
